### ISSUE TITLE
Build issues: File `latex-preamble-styles.tex' not found

### ISSUE THREAD

**Issue by JL102** [oscarlevin/discrete-book#125]
Hello,

I'm trying to run the build steps so I can fix some typos I've found and submit a PR with the fixes. Unfortunately, I'm getting the following errors:
```
! LaTeX Error: File `latex-preamble-styles.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)
```

If I press enter without typing anything, I get the same message once more. I pressed enter without typing anything again, and then:

```
Package hyperref Warning: Rerun to get /PageLabels entry.


Package pgfplots Warning: running in backwards compatibility mode (unsuitable t
ick labels; missing features). Consider writing \pgfplotsset{compat=1.18} into 
your preamble.
 on input line 2195.


! Package pdfpages Error: Cannot find file `images/front.pdf'.

See the pdfpages package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2201 ...pdf[noautoscale=false]{images/front.pdf}
                                                  %
No pages of output.
Transcript written on dmoi.log.
critical: [Errno 2] No such file or directory: 'dmoi.pdf'
##################
Failed to build pdf.  Exiting...

----------------------------------------------------
While running pretext, the following errors occured:

critical: [Errno 2] No such file or directory: 'dmoi.pdf'
----------------------------------------------------
Exception ignored in atexit callback: <function exit_command at 0x7f37f3b00b80>
Traceback (most recent call last):
  File "/home/drak/.local/lib/python3.10/site-packages/pretext/utils.py", line 377, in exit_command
    sys.exit(1)
SystemExit: 1
```

It's also worth noting that when I try to run the command `pretext build pdf -w` as per the build instructions, I get the following error:

```
PreTeXt project found in `/home/drak/OneDrive/Projects/Programming/syncignore_discrete-book`.
Usage: pretext build [OPTIONS] [TARGET]
Try 'pretext build -h' for help.

Error: No such option: -w
```

so I'm just executing `pretext build pdf` to attempt the build.

I am using:

- Debian 12 (bookworm), 
- pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)
- Python 3.10.7
- PreTeXt 1.0.3

How do I fix these issues?

**Comment by oscarlevin** [comment]
Thanks for alerting me to this.  There were a few changes I had to make to work with the updated version of PreTeXt, thanks to my previous hacking to customize things.  I think I have it set up to work now.  Please try to pull the latest commit and rebuild.  Let me know how it goes.

**Comment by JL102** [comment]
@oscarlevin The latex-preamble-styles.tex problem seems to be gone! But unfortunately the dmoi.pdf error is still there. This is the last bit of the build output:

```

! Package pdfpages Error: Cannot find file `external/images/front.pdf'.

See the pdfpages package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2201 ...oscale=false]{external/images/front.pdf}
                                                  %
No pages of output.
Transcript written on dmoi.log.
critical: [Errno 2] No such file or directory: 'dmoi.pdf'
##################
Failed to build pdf.  Exiting...

----------------------------------------------------
While running pretext, the following errors occured:

critical: [Errno 2] No such file or directory: 'dmoi.pdf'
----------------------------------------------------
Exception ignored in atexit callback: <function exit_command at 0x7fd2d2ffcb80>
Traceback (most recent call last):
  File "/home/drak/.local/lib/python3.10/site-packages/pretext/utils.py", line 377, in exit_command
    sys.exit(1)
SystemExit: 1
```

Here's .error_schema.log:
```
/home/drak/OneDrive/Projects/Programming/syncignore_discrete-book/source/dmoi.ptx:4:0:ERROR:RELAXNGV:RELAXNG_ERR_ELEMWRONG: Did not expect element include there
/home/drak/OneDrive/Projects/Programming/syncignore_discrete-book/source/dmoi.ptx:4:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element pretext has extra content: include
```

**Comment by JL102** [comment]
If I comment out line 4 of dmoi.pdf (`<!-- <xi:include href="./bookinfo.ptx"/> -->`), it seems to build... but only the first 18 pages? 

![image](https://user-images.githubusercontent.com/11487870/193281207-569b78f5-c76e-4322-b802-bbdaf5342b01.png)

**Comment by JL102** [comment]
Eyyyy, it worked! The whole pdf built, thanks!

**Comment by oscarlevin** [comment]
Wonderful.  Thanks for reporting this and making the project better.
